export {
  deleteAdminBooking,
  deleteAdminLead,
  deleteAdminMedia,
  fetchAdminBlogPost,
  fetchAdminBookings,
  fetchAdminLeads,
  fetchAdminMedia,
  fetchAdminPageModules,
  loginAdmin,
  logoutAdmin,
  patchAdminBooking,
  patchAdminLead,
  saveAdminBlogPost,
  saveAdminPageModules,
  updateAdminMedia,
  uploadAdminMedia,
} from "@/lib/api/admin-client";
