export { default as CoursesSection } from "./CoursesSection";
export { default as ExperienceSection } from "./ExperienceSection";
export { default as FAQSection } from "./FAQSection";
export { default as FinalCTASection } from "./FinalCTASection";
export { default as HeroSection } from "./HeroSection";
export { default as RishikeshSection } from "./RishikeshSection";
export { default as TeachersSection } from "./TeachersSection";
export { default as TestimonialsSection } from "./TestimonialsSection";
export { default as WelcomeSection } from "./WelcomeSection";
